sudo: required

language: bash

services:
  - docker

before_script:
  - export APP_IMAGE=keboola-component
  - docker -v
  - docker build -t $APP_IMAGE .
  - >-
    docker
    run
    -e SNOWFLAKE_HOST
    -e SNOWFLAKE_DATABASE
    -e SNOWFLAKE_USER
    -e SNOWFLAKE_PASSWORD
    -e SNOWFLAKE_WAREHOUSE
    $APP_IMAGE
    composer ci
