CREATE DATABASE "TRAVIS_SNOWFLAKE_ADAPTER" DATA_RETENTION_TIME_IN_DAYS = 0;
CREATE ROLE "TRAVIS_SNOWFLAKE_ADAPTER";
GRANT OWNERSHIP ON DATABASE "TRAVIS_SNOWFLAKE_ADAPTER" TO ROLE "TRAVIS_SNOWFLAKE_ADAPTER";
CREATE USER "TRAVIS_SNOWFLAKE_ADAPTER"
    PASSWORD = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    DEFAULT_ROLE = "TRAVIS_SNOWFLAKE_ADAPTER";
GRANT ROLE "TRAVIS_SNOWFLAKE_ADAPTER" TO USER "TRAVIS_SNOWFLAKE_ADAPTER";
GRANT ROLE "TRAVIS_SNOWFLAKE_ADAPTER" TO ROLE "ACCOUNTADMIN";
GRANT USAGE ON WAREHOUSE "DEV" TO ROLE "TRAVIS_SNOWFLAKE_ADAPTER";
GRANT USAGE ON DATABASE "TRAVIS_SNOWFLAKE_ADAPTER" TO ROLE "TRAVIS_SNOWFLAKE_ADAPTER";
CREATE SCHEMA "TRAVIS_SNOWFLAKE_ADAPTER"."TRAVIS_SNOWFLAKE_ADAPTER";
GRANT ALL ON SCHEMA "TRAVIS_SNOWFLAKE_ADAPTER"."TRAVIS_SNOWFLAKE_ADAPTER" TO ROLE "TRAVIS_SNOWFLAKE_ADAPTER";
