name: 'GitHub Actions'
'on':
  - push
concurrency: 'ci-${{ github.ref }}'
env:
  APP_IMAGE: keboola/db-adapter-snowflake
  DOCKERHUB_USER: '${{ secrets.DOCKERHUB_USER }}'
  DOCKERHUB_TOKEN: '${{ secrets.DOCKERHUB_TOKEN }}'

  # Snowflake Credentials
  SNOWFLAKE_HOST: "kebooladev.snowflakecomputing.com"
  SNOWFLAKE_WAREHOUSE: "DEV"
  SNOWFLAKE_DATABASE: "GHA_SNOWFLAKE_ADAPTER"
  SNOWFLAKE_USER: "GHA_SNOWFLAKE_ADAPTER"
  SNOWFLAKE_PASSWORD: '${{ secrets.SNOWFLAKE_PASSWORD }}'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Check out the repo'
        uses: actions/checkout@v2
      -
        name: 'Docker login'
        if: env.DOCKERHUB_TOKEN
        run: 'docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"'
      -
        name: 'Build image'
        run: 'docker build -t $APP_IMAGE .'
      - name: 'Run tests'
        run: |
          docker run \
          -e SNOWFLAKE_HOST \
          -e SNOWFLAKE_WAREHOUSE \
          -e SNOWFLAKE_DATABASE \
          -e SNOWFLAKE_USER \
          -e SNOWFLAKE_PASSWORD \
          ${{env.APP_IMAGE}} composer ci